# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-07 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='邮箱')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('sign', models.CharField(default='', max_length=50, verbose_name='签名')),
                ('info', models.CharField(default='', max_length=150, verbose_name='描述')),
                ('avatar', models.ImageField(upload_to='avatar/', verbose_name='头像')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
