# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-07 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='电影名称')),
                ('stype', models.CharField(default='now', max_length=10, verbose_name='上映情况')),
                ('duration', models.CharField(default='100分钟', max_length=20, verbose_name='电影时长')),
                ('region', models.CharField(default='', max_length=20, verbose_name='上映地区')),
                ('score', models.FloatField(default=0.0, verbose_name='评分')),
                ('stars', models.CharField(default='', max_length=200, verbose_name='演员表')),
                ('img_url', models.CharField(default='', max_length=200, verbose_name='海报链接')),
                ('detail_url', models.CharField(default='', max_length=200, verbose_name='详情界面链接')),
                ('release_time', models.CharField(default='', max_length=100, verbose_name='上映时间')),
                ('content', models.TextField(default='', verbose_name='内容')),
            ],
            options={
                'db_table': 'film',
            },
        ),
    ]
