# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-09 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='introduce',
            field=models.CharField(default='', max_length=90, verbose_name='概要'),
        ),
        migrations.AlterField(
            model_name='film',
            name='stars',
            field=models.CharField(default='', max_length=300, verbose_name='演员表'),
        ),
    ]
