# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-28 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20190809_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='introduce',
        ),
    ]
