# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-29 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_remove_film_introduce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='stars',
            new_name='actors',
        ),
        migrations.AddField(
            model_name='film',
            name='directors',
            field=models.CharField(default='', max_length=100, verbose_name='导演表'),
        ),
    ]
